language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8
dist: trusty

deploy:
  provider: heroku
  api_key: "545f6311-690b-48a7-804b-239ae404da0b"
  app: re-senia

before_script:
  - chmod +x gradle
script:
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)
